name:                reactivegame
version:             0.1.0.0
github:              "githubuser/reactivegame"
license:             BSD3
author:              "Alex Tunnicliffe"
maintainer:          "alex@tunnicliffe.com"
copyright:           "2024 Alex Tunnicliffe"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Functional Reactive Programming based basic 2D game engine
# category:            Gaming

description:         Please see the README on GitHub at <https://github.com/githubuser/reactivegame#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- classy-prelude
- directory
- hashable
- parallel
- random
- sdl2
- sdl2-ttf
- sdl2-image
- sdl2-mixer
- sdl2-gfx
- simple-affine-space
- split
- text
- unordered-containers
- vector
- Yampa

library:
  source-dirs: src

executables:
  reactivegame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reactivegame
    - yaml

tests:
  reactivegame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reactivegame
